### ISSUE TITLE
Cannot read properties of undefined (reading 'translations')

### ISSUE THREAD

**Issue by NHLopez** [CodeStitchOfficial/Advanced-Astro-v4-i18n#2]
Hey guys! I cloned the project and installed the dependencies and got this error. No changes were to the code. Something I thought was interesting was my first time installing the project it worked fine. After receiving this error and multiple times of cloning, installing, nothing will change. I had even thought it was the fact I upgraded to astro 4.12.3, but after just starting over I'm stuck.

```
TypeError: Cannot read properties of undefined (reading 'translations')
    at Module.t (/mnt/d/Developement/Phlex Design/Client Projects/Advanced-Astro-v4-i18n-main/i18n:astro:124:14)
    at eval (eval at instantiateModule (file:///mnt/d/Developement/Phlex%20Design/Client%20Projects/Advanced-Astro-v4-i18n-main/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:53441:24), <anonymous>:18:39)
    at 404 (eval at instantiateModule (file:///mnt/d/Developement/Phlex%20Design/Client%20Projects/Advanced-Astro-v4-i18n-main/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:53441:24), <anonymous>:19:12)
    at callComponentAsTemplateResultOrResponse (file:///mnt/d/Developement/Phlex%20Design/Client%20Projects/Advanced-Astro-v4-i18n-main/node_modules/astro/dist/runtime/server/render/astro/render.js:90:31)
    at renderToAsyncIterable (file:///mnt/d/Developement/Phlex%20Design/Client%20Projects/Advanced-Astro-v4-i18n-main/node_modules/astro/dist/runtime/server/render/astro/render.js:132:32)
    at renderPage (file:///mnt/d/Developement/Phlex%20Design/Client%20Projects/Advanced-Astro-v4-i18n-main/node_modules/astro/dist/runtime/server/render/page.js:31:30)
    at lastNext (file:///mnt/d/Developement/Phlex%20Design/Client%20Projects/Advanced-Astro-v4-i18n-main/node_modules/astro/dist/core/render-context.js:135:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callMiddleware (file:///mnt/d/Developement/Phlex%20Design/Client%20Projects/Advanced-Astro-v4-i18n-main/node_modules/astro/dist/core/middleware/callMiddleware.js:21:10)
    at async RenderContext.render (file:///mnt/d/Developement/Phlex%20Design/Client%20Projects/Advanced-Astro-v4-i18n-main/node_modules/astro/dist/core/render-context.js:163:22)
```

I also noticed this:
![image](https://github.com/user-attachments/assets/24fd89d3-b779-419c-8621-901849b79f29)
![image](https://github.com/user-attachments/assets/f4b745bd-66f2-44fd-b3ad-84e6eceba982)

Hopefully that helps, it was just something I noticed. Thank you!

**Comment by BuckyBuck135** [comment]
Hi @NHLopez,
Thanks for the report.
Could you please elaborate:
 * is there a specific page the error happens?
 * OS
 * node version
 
 Thanks.

**Comment by NHLopez** [comment]
Hey @BuckyBuck135, 

Not sure what happened but it works now? I just cloned it fresh and now its fine. 

Before. it would give that error whenever the page transitions. For example, if I do npm start the homepage showed up, when I clicked about, I would see the about page slightly then it would throw the above error so I thought it might be the transitions but when I looked on astros website it was fine.

Either way it works now so thank you so much. Just incase it happens again would you know anything I could do?

**Comment by BuckyBuck135** [comment]
Ok great!
Without being able to reproduce the bug, it's difficult to say where it was coming from. let's hope it doesn't crawl back up again! :)

**Comment by NHLopez** [comment]
Hey @BuckyBuck135 !

I made a 4 minute video of trying to catch the bug. I ended up doing a video from a fresh clone to installing its dependencies to using the site and it crashing. Usually it happens when I try to click links to pages as well but it was fine this time around. I tried to show as much detail as possible. I hope this is helpful in some sort of way since I can't give more information. 

Either way have a great day! :)


https://github.com/user-attachments/assets/19873b9d-f75a-4222-a718-d99c76fadf43

**Comment by BuckyBuck135** [comment]
Hi @netmaster2000,
Thanks for your report. I've reopened the issue. 
I'm currently away for family reasons, so I won't have time to dig into this just now. In the meantime, if you do have some free time to run some debugging tests to try and pinpoint which page / component causes this issue, that would be a tremendous help.

**Comment by BuckyBuck135** [comment]
After some quick tests, I looks like the issue does not impact the production site, which is good. I'll try to tackle this when I have some free time.
`npm run build` + `npm run preview` shows you a copy of the deployed site on localhost.

**Comment by BuckyBuck135** [comment]
Hi guys,
Thank you for your patience. I'm back at the keyboard after a family break.

The error seems to be coming from the custom 404 page. Short term: deleting this 404 page gets rid of the error.

Now, I'm working towards finding a more sustainable solution.

**Comment by BuckyBuck135** [comment]
Hi everyone,
Since Astro patched the issue upstream with [this PR](https://github.com/withastro/astro/pull/12037), I reinstated the custom translated 404 route in the kit.
Make sure you [upgrade Astro](https://docs.astro.build/en/upgrade-astro/) to at least v4.15.9, place `404.astro` in the `routes/` folder and the matching translation in `locales/`, as demonstrated in the kit.
